services:
  - name: lyleauthentic
    type: web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    healthCheckPath: /
